### PR TITLE
Use faster set types

### LINKED ISSUE #50: Use unordered `set`s and `map`s
Maki currently uses `set`s and `map`s in several places to track macro expansions and definitions, but should use the `unordered` variants of these types to improve performance since the ordering of `set` and `map` keys is never important to Maki.

### PR DESCRIPTION
**Pull request by PappasBrent**
Closes #50

### CODE REVIEW

**Comment by SilverMight** [comment]
Code looks good to me but for some reason is running slower for me (about a second on average for a particular file)

**Comment by PappasBrent** [comment]
Do you mean a second slower for a specific file or a second slower on average?
I couldn't notice a difference in speed for running Maki's the test suite but I figured that was just because the test suite was so small.

**Comment by SilverMight** [comment]
About a second on average for a specific large file.

**Comment by PappasBrent** [comment]
What's the exact file? Is it from Bash or one of the other evaluation programs? I can test myself and I'll mark this PR as a draft until I can push changes to actually improve performance since that's the point of this PR.

**Comment by SilverMight** [comment]
> What's the exact file? Is it from Bash or one of the other evaluation programs? I can test myself and I'll mark this PR as a draft until I can push changes to actually improve performance since that's the point of this PR.

y.tab.c (the bison file) from bash - note this is a pretty bad case, didn't notice anything much in smaller files

**Comment by PappasBrent** [comment]
Ok so I took some time today to test the performance of Maki on `y.tab.c` from Bash, and didn't really find a difference in performance.
I ran main-branch Maki on the file with the appropriate compile commands five times, and then the "faster" set types version of Maki on the file five times.
I've attached the script I used to run my experiment to this comment as a text file because GitHub seems to disallow script file attachments.
I've also attached my full results to this comment, but in summary I found that the main branch Maki took 2.01 seconds on average to process the file and the branch of Maki with this PR's changes took 2.02 seconds on average to process the file.
So no real difference.

- Script: [run-maki-on-y-tab.txt](https://github.com/user-attachments/files/15934200/run-maki-on-y-tab.txt) (the build.sh script this runs just configures and builds Maki)
- Main branch Maki runtimes: [runtimes_main_maki.txt](https://github.com/user-attachments/files/15934242/runtimes_main_maki.txt)
- PR branch Maki runtimes: [runtimes_unordered_sets_maki.txt](https://github.com/user-attachments/files/15934241/runtimes_unordered_sets_maki.txt)

**Comment by PappasBrent** [comment]
I'm going to close this PR then since these changes don't seem to have any impact on performance.

**Pull request closed without merging**
